CREATE TABLE setting (
id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
keyname VARCHAR(20),
val VARCHAR(100)
);
--;;
INSERT INTO setting (keyname,val) VALUES ('prefs/score-formula', '[[a b c] v] (* a (* b c))');
