CREATE TABLE scores
(id INTEGER     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 item_id INTEGER,
 score_type_id INTEGER,
 score NUMERIC(20,2));
--;;
ALTER TABLE scores
    ADD CONSTRAINT "SC_TYPE_ID" FOREIGN KEY (score_type_id)
    REFERENCES score_type (id);
--;;
ALTER TABLE scores
    ADD CONSTRAINT "SC_ITEM_ID" FOREIGN KEY (item_id)
    REFERENCES item  (id);
